apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamwiel
  labels:
    app: kamwiel
spec:
  selector:
    matchLabels:
      app: kamwiel
  template:
    metadata:
      labels:
        app: kamwiel
    spec:
      serviceAccountName: kuadrant-reader
      containers:
        - name: kamwiel
          image: kamwiel:latest
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kamwiel
spec:
  selector:
    app: kamwiel
  ports:
    - port: 3000
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuadrant-reader
  namespace: kamwiel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kamwiel
  name: kuadrant-reader-role
rules:
  - apiGroups: ["networking.kuadrant.io"]
    resources: ["apis"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuadrant-reader-rb
subjects:
  - kind: ServiceAccount
    name: kuadrant-reader
    namespace: kamwiel
roleRef:
  kind: Role
  name: kuadrant-reader-role
  apiGroup: "rbac.authorization.k8s.io"
