apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: authorino
    control-plane: controller-manager
  name: authorino-controller-manager
  namespace: kamwiel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorino
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: authorino
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - "--metrics-addr=127.0.0.1:8080"
            - "--enable-leader-election"
          command:
            - "/manager"
          image: quay.io/3scale/authorino:latest
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
        - args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
      terminationGracePeriodSeconds: 10
