apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    app: authorino
  name: authorino-metrics-reader
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
